Perform only one v9/me/preferences call
toggl-open-source/toggldesktop pull request #4343
Opened 2020-08-20 11:00 UTC by atsvirchkova

### 📒 Description
v9/me/preferences and v9/me/preferences/desktop responses are exactly the same, so there should be no reason to perform both calls. We should perform only one of these calls.

### 🕶️ Types of changes

- **Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes

- [ ] context.cc

### 👫 Relationships

 Closes #4324 

### 🔎 Review hints
Test if user settings are updated on user login, on app startup and on full sync.

2020-08-25 14:00 UTC, MartinBriza requested changes
Looks good! I found some smaller things that should be fixed before merging but nothing too serious.

2020-08-28 09:33 UTC, MartinBriza commented on src/model/user.h
> +    void User::LoadAlphaFeaturesFromJSON(const Json::Value& data);
Remove User:: and it will build

2020-08-28 09:55 UTC, atsvirchkova commented on src/model/user.h
> +    void User::LoadAlphaFeaturesFromJSON(const Json::Value& data);
Thank you for help :)

2020-08-28 09:56 UTC, atsvirchkova commented
Moved AlphaFeatures to user class. Now ready for review again.

2020-08-31 16:31 UTC, MartinBriza approved these changes
Thank you. From my testing everything works right and I like the quality of the code, good job!
I'm intentionally just approving but not merging the changes due to the current feature freeze that's in place.

2020-09-08 07:22 UTC, merged