Fix bug when autocomplete mouse selection wasn't working on macOS
toggl-open-source/toggldesktop pull request #4552
Opened 2020-10-16 11:37 UTC by AndrewVebster

### 📒 Description
Fixes the bug when user could not select item from the description autocomplete with a mouse.

### 🕶️ Types of changes
- **Bug fix** (non-breaking change which fixes an issue)
- **Breaking change** (fix or feature that would cause existing functionality to change)

### 🤯 List of changes

### 👫 Relationships
Closes #4548 

### 🔎 Review hints
Test autocomplete in different use cases. This PR can break stuff

2020-10-16 12:50 UTC, skel35 requested changes
The tags list is empty after starting the app before the Edit view is open.
I'm not sure if it's related to this PR, but I can't reproduce it on `master`.

2020-10-16 14:32 UTC, AndrewVebster commented
Updated, please review.
The last two commits are related to tags and also have extended commit message to explain what was done

2020-10-16 15:43 UTC, skel35 requested changes
The description field gets reset in 1-2 secs after selecting an autocomplete item
![desc](https://user-images.githubusercontent.com/16451391/96279435-539f3b00-0fdf-11eb-934d-6b5db23dede9.gif)

2020-10-19 10:20 UTC, AndrewVebster commented
The issue above is also present in a stable version. But I hope I fixed it.

2020-10-19 12:03 UTC, skel35 approved these changes
Tested a bit more, works as expected 👍

2020-10-19 12:04 UTC, merged