Feature/duration dropdown basics
toggl-open-source/toggldesktop pull request #4632
Opened 2020-11-02 07:59 UTC by AndrewVebster

### 📒 Description

This PR adds basic UI for duration dropdown.

### 🕶️ Types of changes
- **New feature** (non-breaking change which adds functionality)

### 🤯 List of changes

### 👫 Relationships
Closes #4590

### 🔎 Review hints

Duration dropdown is hidden under local feature flag. To enable it go to `TimerDurationControl.swift` line 16 and set `isDurationDropdownEnabled` to `true`.

- Test if UI interactions are working as expected
- Test if the duration text field still works as before (especially if the dropdown feature is disabled)

2020-11-02 16:14 UTC, skel35 requested changes
Something I've discovered during testing:
1. The keyboard navigation is not entirely logical.
The user can Shift-Tab into the date field but cannot Tab into it. Either the field is focusable, and both are available, or the field is not focusable (not sure it's a good idea, but the users wouldn't be changing dates in the timer often, plus it's not focusable in the web app, so it's fine with me).
It's also expected that if you Tab into the duration dropdown, then Shift-Tab will revert the action - i.e., close the duration dropdown and put the focus back into the duration field.

2. Pressing Enter while the Start time field is focused should be confirming the action instead of selecting the text. I'd expect that the dropdown gets closed and the focus is back into the duration field where the "seed" duration is updated. This PR is not final, but I expected the keyboard navigation to be a part of it.

3. Again, maybe it's outside of this PR, but enabled and disabled text fields look quite similar for now, so it's something to pay attention to going forward.

2020-11-03 09:38 UTC, AndrewVebster commented on src/ui/osx/TogglDesktop/Common/Views/DropdownWindow.swift
> +            location.y -= -Constants.topPaddingLarge
👍

2020-11-03 09:38 UTC, AndrewVebster commented on src/ui/osx/TogglDesktop/Common/Views/DropdownWindow.swift
> +//  AutoCompleteWindow.swift
👍

2020-11-03 09:45 UTC, AndrewVebster commented
Thanks @skel35 

1. Shift-Tab now closes the dropdown. Was planning to include day-control into keyboard navigation in the scope of #4610. The idea is that we can play with it and decide what will be better.
2. Let's do this in the scope of #4591. The text field will be functioning there. Though I'm not sure if we should close the dropdown on Enter key.
3. Updated, please take a look. We don't have this color in our assets, so used the system color there.

2020-11-03 11:11 UTC, skel35 approved these changes
Looking good now, thanks!

2020-11-03 11:12 UTC, merged