Implement start time update via duration dropdown (mac)
toggl-open-source/toggldesktop pull request #4639
Opened 2020-11-04 09:24 UTC by AndrewVebster

### 📒 Description

PR adds the ability to edit TE start time via duration dropdown

### 🕶️ Types of changes

- **New feature** (non-breaking change which adds functionality)

### 🤯 List of changes

### 👫 Relationships

Closes #4591 

### 🔎 Review hints

Duration dropdown is hidden under local feature flag. To enable it go to `TimerDurationControl.swift` line 16 and set `isDurationDropdownEnabled` to `true`.

Test if interactions make sense and if using the start time and duration text fields work as expected.

2020-11-05 18:35 UTC, skel35 requested changes
The behavior is inconsistent with the web app.
STR
1. Timer is not running.
2. Set the start time to smth (e.g. `20:15`)

AR
The duration is not rounded down to minutes. E.g. `11:39 min`

ER
The duration is rounded down to minutes. E.g. `11:00 min`

2020-11-06 07:33 UTC, AndrewVebster commented on src/toggl_api.cc
> +    Poco::LocalDateTime local;
updated 👍

2020-11-06 08:09 UTC, AndrewVebster commented
I think on the Web app the duration is rounded because they also have an end time field. So after you enter start time the timer goes into "manual" mode and it's a little bit easier (duration = end - start).
Anyway, I did rounding to minutes. Maybe it's better to understand.

2020-11-06 09:56 UTC, skel35 approved these changes
Looks good.
I like both the behavior before the timer is started, and while the timer is running.

The web app's behavior is indeed different as it switches into the manual mode, so consistency is not so important. But having round minutes seems more clear and satisfying, so I like it more anyway. Feel free to ask more people about it if you think the previous behavior makes more sense.

2020-11-06 10:07 UTC, merged