Implement date control on duration dropdown (mac)
toggl-open-source/toggldesktop pull request #4646
Opened 2020-11-06 10:25 UTC by AndrewVebster

### 📒 Description
Adds working date control to duration dropdown along with an embedded calendar.

### 🕶️ Types of changes

- **New feature** (non-breaking change which adds functionality)

### 🤯 List of changes

### 👫 Relationships

Closes #4611

### 🔎 Review hints

Duration dropdown is hidden under local feature flag. To enable it go to `TimerDurationControl.swift` line 28 and set `isDurationDropdownEnabled` to `true`

2020-11-06 12:33 UTC, AndrewVebster commented
Saw that changing date won't round duration to minutes. Will try to do the same as with start time. Sorry, do not review for now

2020-11-06 13:53 UTC, AndrewVebster commented
Updated, ready for review again

2020-11-06 13:53 UTC, AndrewVebster commented
Will make PR for keyboard navigation and analytics right after this one merged

2020-11-06 16:07 UTC, skel35 requested changes
Bug discovered:
STR
1.Timer is not running
2. Set the time to 30 mins after the current time

AR
Crash
![image](https://user-images.githubusercontent.com/16451391/98387761-7ced3d00-205a-11eb-9295-9b8e90ca03af.png)

I've also noticed that opening the calendar takes a long time (~1sec). Do you think there's anything that can be done to make it faster?

2020-11-09 08:23 UTC, AndrewVebster commented
thanks for catching this, updated PR

2020-11-09 08:23 UTC, AndrewVebster commented on src/ui/osx/TogglDesktop/Features/Timer/TimerViewController/TimerViewModel.swift
> +        // `newDay` is always "today" or "yesterday"
updated, thanks

2020-11-09 10:34 UTC, skel35 approved these changes
couldn't find any more bugs, works just as I'd expect it 👍

2020-11-09 10:34 UTC, merged