[WIP] Fix resizing stops when TE update arrives
toggl-open-source/toggldesktop pull request #4662
Opened 2020-11-12 16:13 UTC by atsvirchkova

### 📒 Description
Updating of time entry blocks is blocked if any of the items is being grabbed.

### 🕶️ Types of changes

- **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes

### 👫 Relationships

 Closes #4563 

### 🔎 Review hints
To be reviewed after #4645 is merged.

2020-11-13 16:30 UTC, skel35 requested changes
Looks quite good, nice job!
One thing that's bothering me a bit - sometimes the tooltip does not update when resizing the running TE, especially when resizing twice in a row. I could not reproduce this issue when resizing the stopped TEs.
![AOR3PPsfyp](https://user-images.githubusercontent.com/16451391/99095811-44131200-25de-11eb-8ba8-8d0d190179a0.gif)

2020-11-16 19:44 UTC, atsvirchkova commented
The issue with tooltip is finally fixed now. Found another bug meanwhile: duration on tooltip (and description) for running TE does not coincide with that on timer. I reported it separately #4676.

2020-11-17 10:04 UTC, skel35 requested changes
In Timeline.xaml.cs there's already a logic that assigns DataContext, sets PlacementTarget and shows the popup. Partially duplicating this logic in another class makes little sense to me both from the UX and from the code perspective.

2020-11-17 10:04 UTC, skel35 commented on src/ui/windows/TogglDesktop/TogglDesktop/ui/controls/TimelineRunningTimeEntryBlock.xaml.cs
> +            _popup.Popup.PlacementTarget = this;
Why did you decide to change the logic of the popup positioning for the running time entry?
Old issues like this one are back now.
![image](https://user-images.githubusercontent.com/16451391/99375486-76698b80-28cc-11eb-8a55-7aed2abfdcab.png)

2020-11-17 10:26 UTC, atsvirchkova commented
This was the main pain point of yesterday's investigation. The reason for moving out the existing logic is that it simply didn't work the way it was, I mean the bug with not-updating tooltip stayed for running TE. I've just pushed the branch https://github.com/toggl-open-source/toggldesktop/tree/test/timeline_ui/resizing_bugfix where the separate logic for running TE is commented, and the existing in Timeline.xaml.cs is reused. You'll be able to reproduce the tooltip bug:
1. Grab running TE start and move it, then drop it but don't move the mouse (so that the tooltip stays).
2. Then grab it once more and move again, you'll see the duration and start time on tooltip won't change.

Though I still don't understand how that logic different from this one.

2020-11-17 11:48 UTC, skel35 commented
@atsvirchkova https://github.com/toggl-open-source/toggldesktop/tree/test/timeline_ui/resizing_bugfix is exactly the same as the current one.

2020-11-17 11:51 UTC, atsvirchkova commented
Sorry, forgot to commit the changes. Now it's different.

2020-11-17 12:10 UTC, skel35 commented
Maybe you misunderstood me, but I didn't mean the separate popup (although it would be very good to understand why it doesn't work without a separate popup). The issue in this PR is that the popup positioning is messed up (see screenshot above), and the positioning logic isn't reused for some reason.
I've just taken your branch and made a couple of small changes: https://github.com/toggl-open-source/toggldesktop/tree/fix/timeline_ui/resizing-v2. I can't reproduce the positioning issue anymore and the code is reused.
It's quick&dirty fix but I hope you get the point.

2020-11-17 12:16 UTC, atsvirchkova commented
Thank you. Yeh, I understand the issue with the positioning. It's not a big deal to reuse the positioning logic, I will move it to this branch. I just spent quite a lot of time trying to make it work with the same popup and gave up at the end.

2020-11-17 13:36 UTC, atsvirchkova commented
Popup logic is fixed now.

2020-11-17 14:24 UTC, skel35 approved these changes
Resizing works nice and smooth now. Good job!

2020-11-17 14:24 UTC, merged