Fix TEs are displayed overlapped when they are actually not
toggl-open-source/toggldesktop pull request #4707
Opened 2020-11-23 14:20 UTC by atsvirchkova

### 📒 Description
Fix TEs are displayed overlapped when they are actually not.

### 🕶️ Types of changes

- **Bug fix** (non-breaking change which fixes an issue)

### 🤯 List of changes

### 👫 Relationships

Closes #4673 

### 🔎 Review hints
Some refactoring is done is scope if this bugfix:
1. Started and Ended time stamps are removed from `TimeEntryBlock` class, as all necessary info can be got from `VerticalOffset` and `Height` properties.
2. Height and offset properties now correspond to time stamps strictly, the case of zero time entry length is handled in xaml code by setting `MinHeight`.
3. There is now  a precision constant introduced for doubles comparison, so everything that has an overlap less than 10^-5 is not considered to be an actual overlap.

2020-11-24 15:25 UTC, skel35 requested changes
Bug discovered.

STR
1. Click the running time entry to open the Edit view
2. Close the Edit view
3. Switch days

AR
Edit view sometimes opens up by itself

Note: when TE is stopped the issue is still happening

2020-11-24 17:51 UTC, atsvirchkova commented
@skel35 I cannot reproduce the bug. There is logic in the code to close Edit view if date has changed (by closing I mean calling `Toggl.Edit` which may also open Edit view if it's closed) and I think this may cause the issue. But then it should be reproducible in master also, there was no change to this logic in this PR.

2020-11-24 17:56 UTC, skel35 commented
You're right that it is reproducible on `master` as well.
It's weird that you can't reproduce it, it's straightforward. I'll open an issue.

2020-11-24 17:58 UTC, skel35 commented
OK, now I can't reproduce it myself 😄 
I will try to figure this out tomorrow, otherwise, we'll need to look into the code to find out how this state can be achieved.

2020-11-24 18:04 UTC, atsvirchkova commented
I suppose, you have to be faster than your PC to reproduce this bug. I think it happens when `SelectedForEditTEId` is not nulled yet after edit view close, and you change the date at that time.

2020-11-25 09:51 UTC, atsvirchkova commented
Fixed the two mentioned issues. As for making a `BehaviorSubject<(Started, Ended)>` and using it for `ChangeStartTime` and `ChangeEndTime` - this will result into calling this two functions every time a new value arrives which is not desirable as they call lib functions that trigger saving to database.

2020-11-25 13:41 UTC, skel35 approved these changes
Looks good!
And the bug with running time entry displayed on the future days is also fixed 👍

2020-11-25 13:41 UTC, merged