[WIP] Unit tests for ConvertTimeEntriesToBlocks and GenerateGapTimeEntryBlocks
toggl-open-source/toggldesktop pull request #4731
Opened 2020-12-04 16:42 UTC by atsvirchkova

### 📒 Description

### 🕶️ Types of changes

 - **Unit tests**

### 🤯 List of changes

### 👫 Relationships

 Closes #4696 

### 🔎 Review hints
It's currently not possible to test that part of `ConvertTimeEntriesToBlocks`, where `runningEntry` comes into play, because of dependency on `DateTime.Now`. Probably, I'll introduce the `now` parameter in this method for that purpose.

2020-12-07 18:11 UTC, skel35 requested changes

2020-12-07 18:11 UTC, skel35 commented on src/ui/windows/TogglDesktop/TogglDesktop.Tests/TimelineConvertTimeEntriesToBlocksTests.cs
> +                    (timeEntryList[0].GUID, TimeToHeight(timeEntryList[0].Started - _selectedDateUnix, scaleMode),
This part of the tests is quite hard to read.
My suggestion to improve the readability:
1. Extract constants, like T1 = 0, T2 = 50, T3 = 100, T4 = 150, T5 = 200.
2. Use theses constants in your expected blocks list, e.g. `TimeToHeight(T1, scaleMode)` is easier to read than `TimeToHeight(timeEntryList[0].Started - _selectedDateUnix, scaleMode)`.

2020-12-09 08:56 UTC, atsvirchkova commented
Is this situation possible?
- what if TE list has a TE with the same GUID as the running TE has
Currently in our code, TEs with the same GUID are considered equal, and such TEs will appear in the final list only once. What should be the expected behavior?

2020-12-09 08:59 UTC, skel35 commented
> Is this situation possible?
> 
> * what if TE list has a TE with the same GUID as the running TE has
>   Currently in our code, TEs with the same GUID are considered equal, and such TEs will appear in the final list only once. What should be the expected behavior?

1. We don't guarantee that it's impossible.
2. Why do we need this line then? https://github.com/toggl-open-source/toggldesktop/blob/f97b9f9cede72e78a1d1a42886473edea858be58/src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimelineViewModel.cs#L223

2020-12-09 11:27 UTC, atsvirchkova commented
> > Is this situation possible?
> > 
> > * what if TE list has a TE with the same GUID as the running TE has
> >   Currently in our code, TEs with the same GUID are considered equal, and such TEs will appear in the final list only once. What should be the expected behavior?
> 
> 1. We don't guarantee that it's impossible.
> 2. Why do we need this line then? https://github.com/toggl-open-source/toggldesktop/blob/f97b9f9cede72e78a1d1a42886473edea858be58/src/ui/windows/TogglDesktop/TogglDesktop/ui/ViewModels/TimelineViewModel.cs#L223

I checked and yes, it may happen at the moment when the timer is being stopped. We receive a new list with already stopped TE, but `runningTE` is still not nulled. Currently we include the first met one, and omit the second. Not sure what the correct behavior should be.

2020-12-09 11:30 UTC, atsvirchkova commented
Fixed all the issues mentioned above. Also did a test for the situation with running TE have same guid as the one from the list. It reproduces the behavior of real application: `now` time is the same as `Ended` for this TE.

2020-12-09 11:43 UTC, skel35 commented on src/ui/windows/TogglDesktop/TogglDesktop.Tests/TimelineConvertTimeEntriesToBlocksTests.cs
> +        private static readonly ulong T1 = 0;
why not `const`? 😄

2020-12-09 11:44 UTC, skel35 approved these changes
Looks good

2020-12-09 11:49 UTC, atsvirchkova commented on src/ui/windows/TogglDesktop/TogglDesktop.Tests/TimelineConvertTimeEntriesToBlocksTests.cs
> +        private static readonly ulong T1 = 0;
Fixed

2020-12-09 12:35 UTC, merged